[env]
# WGPU_BACKEND = { value = "vulkan", force = true }
WGPU_BACKEND = { value = "dx12", force = true }

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=off"]
